---
apiVersion: v1
kind: Namespace
metadata:
  labels: # https://github.com/bitnami/charts/pull/17388
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: ers
---
# You must still deploy kafka and postgresql with their upstream manifests
# and create a secret called ers-secret.
# It MUST have the following keys defined:
# ERS_DBWRITER_KAFKA_HOST, ERS_DBWRITER_KAFKA_PORT,
# ERS_DBWRITER_HOST, ERS_DBWRITER_PORT
# ERS_DBWRITER_NAME
# ERS_DBWRITER_USER, ERS_DBWRITER_PASS
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: ers-dbwriter
    app.kubernetes.io/component: ers-dbwriter
  name: erskafka
  namespace: ers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erskafka
  template:
    metadata:
      labels:
        app: erskafka
        app.kubernetes.io/app: ers-dbwriter
        app.kubernetes.io/component: ers-dbwriter
    spec:
      containers:
      - image: ghcr.io/dune-daq/pocket-ersdbwriter:latest
        name: erskafka
        envFrom:
        - secretRef:
            name: ers-secret
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          runAsNonRoot: true
          runAsUser: 11000
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 11000
