FROM cern/cc7-base

ARG ERSVERSION=dunedaq-v4.1.1  # For issue.proto from ers
ARG LOCALPYDIR=/microservices_python

RUN yum clean all \
  && yum install gcc make git unzip openssl11 openssl11-devel bzip2-devel libpq-devel libffi-devel zlib-static -y \
  && yum clean all

RUN yum --enablerepo=cernonly -y install oracle-instantclient12.1-devel \
 && yum --enablerepo=cernonly -y install oracle-instantclient-tnsnames.ora

# JCF, Sep-11-2023:
# Since after the openssl11 installation, above, there are two openssl's in the image, I need to isolate
# openssl 1.1.1 for the Python build via creating softlinks in a new directory 

RUN mkdir /ssldir && ln -s /usr/include/openssl11 /ssldir/include && \
 ln -s /usr/lib64/openssl11 /ssldir/lib && cd /ssldir/lib && rm -f libcrypto.so libssl.so && \
 ln -s /lib64/libcrypto.so.1.1.1k libcrypto.so && ln -s /lib64/libssl.so.1.1.1k libssl.so

RUN curl https://www.python.org/ftp/python/3.9.16/Python-3.9.16.tgz > Python-3.9.16.tgz && tar -zxvf Python-3.9.16.tgz 

WORKDIR /Python-3.9.16
RUN ./configure --with-openssl=/ssldir --enable-optimizations \
 && make altinstall \
 && /usr/local/bin/python3.9 -m pip install --upgrade pip
WORKDIR /

RUN cd /usr/local/bin/ && ln -s python3.9 python3

COPY requirements.txt /
RUN pip install -r requirements.txt

RUN pip install git+https://github.com/DUNE-DAQ/elisa_client_api.git

# protoc-24.3-linux-x86_64.zip is the latest zipfile available as of Sep-15-2023
# See also https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os

RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v24.3/protoc-24.3-linux-x86_64.zip && \
  unzip protoc-24.3-linux-x86_64.zip && \
  curl -O https://raw.githubusercontent.com/DUNE-DAQ/ers/$ERSVERSION/schema/ers/issue.proto && \
  mkdir -p $LOCALPYDIR/ers && \
  protoc --python_out=$LOCALPYDIR/ers issue.proto

ENV PYTHONPATH=$LOCALPYDIR:$PYTHONPATH

# This ensures the container will run as non-root by default. Hat tip Pat Riehecky.
# [Commented out so various entrypoint.sh scripts as of Sep-12-2023 continue to work, to be addressed later]
# USER 60000:0
 
