---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline # unified image runs as root :(
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: runservices
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: runregistry-rest
    app.kubernetes.io/component: runregistry-rest
  name: runregistry-rest
  namespace: runservices
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: runregistry-rest
      app.kubernetes.io/component: runregistry-rest
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/app: runregistry-rest
        app.kubernetes.io/component: runregistry-rest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - image: ghcr.io/dune-daq/microservices:latest
        name: runregistry-rest
        env:
         - name: MICROSERVICE
           value: runregistry-rest
        envFrom:
        - secretRef:
            name: run-db-secret
        ports:
        - containerPort: 5005
          name: http
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /uploads
          name: uploads-volume
      volumes: # persistance is not required at this time
      - name: uploads-volume
        emptyDir:
          sizeLimit: 20Gi
      securityContext:
        fsGroup: 11000
