---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline # unified image runs as root :(
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: runservices
---
# You must still deploy postgresql with its manifests from upstream
# and create a secret called runservices-postgresql-svcbind-custom-user with the required keys.
# The ServiceBinding secret from bitnami is such a secret.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  name: runnumber-rest
  namespace: runservices
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: runnumber-rest
      app.kubernetes.io/component: runnumber-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/app: runnumber-rest
        app.kubernetes.io/component: runnumber-rest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - image: ghcr.io/dune-daq/microservices:latest
        imagePullPolicy: Always
        name: runnumber-rest
        env:
        - name: MICROSERVICE
          value: runnumber-rest
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: runservices-postgresql-svcbind-custom-user
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /microservices/runregistry-rest/uploads
          name: uploads-volume
      volumes: # added in prep for merge to single run service
      - name: uploads-volume
        emptyDir:
          sizeLimit: 20Gi
      securityContext:
        fsGroup: 11000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  name: runnumber-rest
  namespace: runservices
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  type: ClusterIP
