---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: daqconfig
---
# You must still deploy mongodb with its manifests from upstream
# and create a secret called daqconfig-mongodb-svcbind-daqconfig with the required keys.
# The ServiceBinding secret from bitnami is such a secret.
# https://github.com/bitnami/charts/issues/17411
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: config-utility
    app.kubernetes.io/component: config-utility
  name: config-utility
  namespace: daqconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: config-utility
      app.kubernetes.io/component: config-utility
  template:
    metadata:
      labels:
        app.kubernetes.io/app: config-utility
        app.kubernetes.io/component: config-utility
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: daqconfig-mongodb-svcbind-daqconfig
        - name: MONGO_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: daqconfig-mongodb-svcbind-daqconfig
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: daqconfig-mongodb-svcbind-daqconfig
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: daqconfig-mongodb-svcbind-daqconfig
        - name: MONGO_DBNAME
          valueFrom:
            secretKeyRef:
              key: database
              name: daqconfig-mongodb-svcbind-daqconfig
        image: ghcr.io/dune-daq/daqconfig-service:v1.0.1
        name: daqconfig-service
        ports:
        - containerPort: 5003
          name: http
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          runAsNonRoot: true
          runAsUser: 11000
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 11000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: config-utility
    app.kubernetes.io/component: config-utility
  name: daqconfig
  namespace: daqconfig
spec:
  ports:
  - port: 5003
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/app: config-utility
    app.kubernetes.io/component: config-utility
  type: ClusterIP
