incrementRunNum = "INSERT INTO RUN_SCHEMA.RUN_NUMBER (RN, START_TIME, FLAG, STOP_TIME) SELECT RN + 1, CURRENT_TIMESTAMP, FALSE, CURRENT_TIMESTAMP FROM RUN_SCHEMA.RUN_NUMBER ORDER BY RN DESC LIMIT 1"

getRunNum = "select RN from RUN_SCHEMA.RUN_NUMBER order by RN DESC limit 1"

getRunTime = "select START_TIME, STOP_TIME from RUN_SCHEMA.RUN_NUMBER where RN=%(runNum)s"

updateStopTimestamp = "update RUN_SCHEMA.RUN_NUMBER set STOP_TIME=CURRENT_TIMESTAMP where RN=%(runNum)s"

