apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: ers
---
# You must still deploy kafka and postgresql with their upstream manifests
# You must still create the required secret
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: ers-protobuf-dbwriter
    app.kubernetes.io/name: ers-protobuf-dbwriter
    app.kubernetes.io/component: ers-protobuf-dbwriter
  name: ersstream-dbwriter
  namespace: ers
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: ers-protobuf-dbwriter
      app.kubernetes.io/name: ers-protobuf-dbwriter
      app.kubernetes.io/component: ers-protobuf-dbwriter
  template:
    metadata:
      labels:
        app.kubernetes.io/app: ers-protobuf-dbwriter
        app.kubernetes.io/name: ers-protobuf-dbwriter
        app.kubernetes.io/component: ers-protobuf-dbwriter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      automountServiceAccountToken: false
      hostUsers: false
      containers:
        - image: ghcr.io/dune-daq/microservices:9685
          imagePullPolicy: Always
          name: ers-protobuf-dbwriter
          env:
            - name: MICROSERVICE
              value: ers-protobuf-dbwriter
            - name: ERS_DBWRITER_KAFKA_BOOTSTRAP_SERVER
              value: dune-daq.kafka.svc.cluster.local:9092
            - name: ERS_DBWRITER_KAFKA_TIMEOUT_MS
              value: "500"
            - name: ERS_DBWRITER_KAFKA_GROUP
              value: ers-protobuf-dbwriter
            - name: ERS_DBWRITER_DB_TABLENAME
              value: ERSstream
            - name: ERS_DBWRITER_DB_URI
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: ers-postgresql-svcbind-custom-user
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            runAsUser: 11000
            runAsGroup: 11000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            sizeLimit: 256Mi
      securityContext:
        fsGroup: 11000
