apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline # unified image runs as root :(
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: opmon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: opmon-protobuf-dbwriter
    app.kubernetes.io/component: opmon-protobuf-dbwriter
  name: opmonstream-dbwriter
  namespace: opmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opmon-protobuf-dbwriter
  template:
    metadata:
      labels:
        app: opmon-protobuf-dbwriter
        app.kubernetes.io/app: opmon-protobuf-dbwriter
        app.kubernetes.io/component: opmon-protobuf-dbwriter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      automountServiceAccountToken: false
      containers:
        - image: ghcr.io/dune-daq/microservices:mroda-opmon_protobuf ## TBC
          imagePullPolicy: Always
          name: opmon-protobuf-dbwriter
          env:
            - name: MICROSERVICE
              value: opmon-protobuf-dbwriter
            - name: OPMON_DBWRITER_KAFKA_BOOTSTRAP_SERVER
              value: dune-daq.kafka.svc.cluster.local:9092
            - name: OPMON_DBWRITER_INFLUX_USER
              value: user
            - name: OPMON_DBWRITER_INFLUX_PASSWORD
              value: pass
            - name: OPMON_DBWRITER_INFLUX_HOST
              value: opmon-influxdb.opmon.svc
            - name: OPMON_DBWRITER_INFLUX_PORT
              value: "8086"
            - name: OPMON_DBWRITER_KAFKA_GROUP
              value: opmon-protobuf-dbwriter
            - name: OPMON_DBWRITER_SUBSCRIBER_TIMEOUT_MS
              value: "5000"
            - name: OPMON_DBWRITER_TOPIC
              value: opmon_stream
            - name: OPMON_DBWRITER_TABLE
              value: opmon_protobuf_v1
            - name: OPMON_DBWRITER_BATCH_SIZE_MS
              value: "800"
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 8Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 11000
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        fsGroup: 11000
