FROM cern/alma9-base

ARG ERSVERSION=v1.5.2  # For issue.proto from ers
ARG ERSKAFKAVERSION=v1.5.4  # For ERSSubscriber.py from erskafka
ARG OPMONLIBVERSION=v2.0.0  # For opmon_entry.proto from opmonlib
ARG KAFKAOPMONVERSION=v2.0.0  # For OpMonSubscriber.py from kafkaopmon

ARG VENV_PATH=/opt/venv
ENV \
    APP_ROOT=/opt/app        \
    APP_DATA=/opt/data       \
    HOME=/opt/app            \
    PYTHONUNBUFFERED=1       \
    PIP_NO_CACHE_DIR=1

ENV PATH="${VENV_PATH}/bin:$PATH"

RUN mkdir -p ${APP_ROOT} ${APP_DATA} ${VENV_PATH} && chmod 1777 ${APP_DATA}
WORKDIR ${APP_ROOT}

# Install base python bits
# Install required devel bits
RUN yum clean expire-cache \
    && yum -y install git python3-pip python3-pip-wheel \
    && yum -y install make gcc python3-devel krb5-devel libffi-devel libpq-devel postgresql \
    && yum clean all

# Can drop when migration to sqlalchemy is complete since we're using the thin client there
RUN curl -O https://download.oracle.com/otn_software/linux/instantclient/1919000/oracle-instantclient19.19-basic-19.19.0.0.0-1.el9.x86_64.rpm \
    && yum -y install libaio libnsl \
    && rpm -iv oracle-instantclient19.19-basic-19.19.0.0.0-1.el9.x86_64.rpm

# setup venv
RUN python3 -m venv ${VENV_PATH}

COPY requirements.txt ${VENV_PATH}/
RUN ${VENV_PATH}/bin/pip install --no-cache-dir -r ${VENV_PATH}/requirements.txt \
    && rm -rf /root/.cache ${HOME}/.cache ${VENV_PATH}/pip-selfcheck.json ${VENV_PATH}/requirements.txt

# protoc-24.3-linux-x86_64.zip is the latest zipfile available as of Sep-15-2023
# See also https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os
# setup protobuf schemas
RUN curl -fSL -O https://github.com/protocolbuffers/protobuf/releases/download/v24.3/protoc-24.3-linux-x86_64.zip \
    && yum -y install unzip \
    && unzip protoc-24.3-linux-x86_64.zip \
    && echo "Installing https://raw.githubusercontent.com/DUNE-DAQ/ers/${ERSVERSION}/schema/ers/issue.proto" \
    && curl -fSL -O https://raw.githubusercontent.com/DUNE-DAQ/ers/$ERSVERSION/schema/ers/issue.proto \
    && mkdir -p $LOCALPYDIR/ers \
    && ./bin/protoc --python_out=$LOCALPYDIR/ers issue.proto \
    && echo "Installing https://raw.githubusercontent.com/DUNE-DAQ/opmonlib/${OPMONLIBVERSION}/schema/opmonlib/opmon_entry.proto" \
    && curl -fSL -O https://raw.githubusercontent.com/DUNE-DAQ/opmonlib/$OPMONLIBVERSION/schema/opmonlib/opmon_entry.proto \
    && mkdir -p $LOCALPYDIR/opmonlib \
    && ./bin/protoc --python_out=$LOCALPYDIR/opmonlib -I${APP_ROOT} -I/include opmon_entry.proto

# fetch ERS python bindings
RUN mkdir -p $LOCALPYDIR/erskafka \
    && echo "Installing https://raw.githubusercontent.com/DUNE-DAQ/erskafka/$ERSKAFKAVERSION/python/erskafka/ERSSubscriber.py" \
    && curl -fSL https://raw.githubusercontent.com/DUNE-DAQ/erskafka/$ERSKAFKAVERSION/python/erskafka/ERSSubscriber.py -o $LOCALPYDIR/erskafka/ERSSubscriber.py \
    && mkdir -p $LOCALPYDIR/kafkaopmon \
    && echo "Installing https://raw.githubusercontent.com/DUNE-DAQ/kafkaopmon/${KAFKAOPMONVERSION}/python/kafkaopmon/OpMonSubscriber.py" \
    && curl -fSL https://raw.githubusercontent.com/DUNE-DAQ/kafkaopmon/$KAFKAOPMONVERSION/python/kafkaopmon/OpMonSubscriber.py -o $LOCALPYDIR/kafkaopmon/OpMonSubscriber.py

# elisa_client_api and CERN kerberos needed by the logbook microservice at NP04
RUN git clone --depth 1 -b develop https://github.com/DUNE-DAQ/elisa_client_api.git \
    && ${VENV_PATH}/bin/pip install --no-cache-dir ./elisa_client_api \
    && rm -rf /root/.cache ${HOME}/.cache ${VENV_PATH}/pip-selfcheck.json elisa_client_api
