FROM ghcr.io/dune-daq/microservices_dependencies:latest

RUN git clone https://github.com/DUNE-DAQ/microservices -b johnfreeman/daq-deliverables_issue105_standard_image

ENTRYPOINT ["/microservices/entrypoint.sh"]
