FROM docker.io/almalinux:10

ARG ERSVERSION=v1.5.2  # For issue.proto from ers
ARG ERSKAFKAVERSION=v1.5.4  # For ERSSubscriber.py from erskafka
ARG OPMONLIBVERSION=v2.0.0  # For opmon_entry.proto from opmonlib
ARG KAFKAOPMONVERSION=v2.0.0  # For OpMonSubscriber.py from kafkaopmon

ARG VENV_PATH=/opt/venv
ENV \
    APP_ROOT=/opt/app        \
    APP_DATA=/opt/data       \
    HOME=/opt/app            \
    PYTHONUNBUFFERED=1       \
    PIP_NO_CACHE_DIR=1

ENV PATH="${VENV_PATH}/bin:$PATH"

RUN mkdir -p ${APP_ROOT} ${APP_DATA} ${VENV_PATH}
WORKDIR ${APP_ROOT}

# Install base python bits
# Install required devel bits
RUN yum clean expire-cache \
    && yum -y install git python3-pip python3-pip-wheel \
    && yum -y install make gcc python3-devel krb5-devel libffi-devel libpq-devel postgresql \
    && yum clean all

# setup venv
RUN python3 -m venv ${VENV_PATH}

COPY requirements.txt ${VENV_PATH}/
RUN ${VENV_PATH}/bin/pip install --no-cache-dir -r ${VENV_PATH}/requirements.txt \
    && rm -rf /root/.cache ${HOME}/.cache ${VENV_PATH}/pip-selfcheck.json

# setup protobuf schemas
RUN yum clean all \
    && yum -y install epel-release \
    && crb enable && yum -y install protobuf-compiler protobuf-devel \
    && yum clean all

RUN echo "Installing https://raw.githubusercontent.com/DUNE-DAQ/ers/${ERSVERSION}/schema/ers/issue.proto" \
    && curl -O https://raw.githubusercontent.com/DUNE-DAQ/ers/${ERSVERSION}/schema/ers/issue.proto \
    && mkdir -p ${VENV_PATH}/ers \
    && protoc --python_out=${VENV_PATH}/ers issue.proto \
    && echo "Installing https://raw.githubusercontent.com/DUNE-DAQ/opmonlib/${OPMONLIBVERSION}/schema/opmonlib/opmon_entry.proto" \
    && curl -O https://raw.githubusercontent.com/DUNE-DAQ/opmonlib/${OPMONLIBVERSION}/schema/opmonlib/opmon_entry.proto \
    && mkdir -p ${VENV_PATH}/opmonlib \
    && protoc --python_out=${VENV_PATH}/opmonlib -I${APP_ROOT} opmon_entry.proto

# fetch ERS python bindings
RUN mkdir -p ${VENV_PATH}/erskafka \
    && echo "Installing https://raw.githubusercontent.com/DUNE-DAQ/erskafka/$ERSKAFKAVERSION/python/erskafka/ERSSubscriber.py" \
    && curl https://raw.githubusercontent.com/DUNE-DAQ/erskafka/$ERSKAFKAVERSION/python/erskafka/ERSSubscriber.py -o ${VENV_PATH}/erskafka/ERSSubscriber.py \
    && mkdir -p ${VENV_PATH}/kafkaopmon \
    && echo "Installing https://raw.githubusercontent.com/DUNE-DAQ/erskafka/$ERSKAFKAVERSION/python/erskafka/ERSSubscriber.py" \
    && curl https://raw.githubusercontent.com/DUNE-DAQ/kafkaopmon/${KAFKAOPMONVERSION}/python/kafkaopmon/OpMonSubscriber.py -o ${VENV_PATH}/kafkaopmon/OpMonSubscriber.py

# elisa_client_api and CERN kerberos needed by the logbook microservice at NP04
COPY cern.repo /etc/yum.repos.d/
RUN yum clean expire-cache \
    && yum -y install krb5-workstation cern-krb5-conf \
    && yum clean all

RUN git clone https://github.com/DUNE-DAQ/elisa_client_api.git \
    && ${VENV_PATH}/bin/pip install --no-cache-dir ./elisa_client_api \
    && rm -rf /root/.cache ${HOME}/.cache ${VENV_PATH}/pip-selfcheck.json
