---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline # unified image runs as root :(
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: logbook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: logbook
    app.kubernetes.io/component: logbook
  name: logbook
  namespace: logbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: logbook
      app.kubernetes.io/component: logbook
  template:
    metadata:
      labels:
        app.kubernetes.io/app: logbook
        app.kubernetes.io/component: logbook
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - image: ghcr.io/dune-daq/microservices:latest
        name: logbook
        env:
        - name: MICROSERVICE
          value: logbook
        - name: HARDWARE
          value: XXXXXXXXXXXXX
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: YYYY
              name: XXXXX
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: YYYY
              name: XXXXX
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 11000
