---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline # unified image runs as root :(
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: runservices
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  name: runnumber-rest
  namespace: {{ DUNE_runservices.namespace }}
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/app: runnumber-rest
      app.kubernetes.io/component: runnumber-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/app: runnumber-rest
        app.kubernetes.io/component: runnumber-rest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ kubernetes_label.worker }}
                operator: Exists
      containers:
      - image: ghcr.io/dune-daq/microservices:latest
        name: runnumber-rest
        env:
        - name: MICROSERVICE
          value: runnumber-rest
        envFrom:
        - secretRef:
            name: run-db-secret
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 11000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      imagePullPolicy: Always
      securityContext:
        fsGroup: 11000
