---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kluctl.io/skip-delete-if-tags: "true"
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: baseline # unified image runs as root :(
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
  name: {{ DUNE_runservices.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  name: runnumber-rest
  namespace: {{ DUNE_runservices.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: runnumber-rest
      app.kubernetes.io/component: runnumber-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/app: runnumber-rest
        app.kubernetes.io/component: runnumber-rest
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: {{ kubernetes_label.worker }}
               operator: Exists
      initContainers:
      - name: wait-for-run-postgres
        image: busybox:1.28
        command: ['sh','-c', 'until nc -z runservices-postgresql.runservices.svc.cluster.local 5432; do echo "Waiting for PostgreSQL"; sleep 2; done']
      containers:
      - name: runnumber-rest
        env:
        - name: MICROSERVICE
          value: runnumber-rest
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: runservices-postgresql-svcbind-custom-user
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 8Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 11000
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 11000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  name: runnumber-rest
  namespace: runservices
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app.kubernetes.io/app: runnumber-rest
    app.kubernetes.io/component: runnumber-rest
  type: ClusterIP
