name: Docker Image CI

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ghcr.io/dune-daq/alma-9:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          COMMIT_SHA_SHORT=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c 1-4)
          docker build -t ghcr.io/dune-daq/microservices_dependencies:latest -f dockerfiles/Dockerfile.microservices_dependencies .
          docker build -t ghcr.io/dune-daq/microservices:$COMMIT_SHA_SHORT -f dockerfiles/Dockerfile.microservices .
      - name: Push Docker image
        run: |
          COMMIT_SHA_SHORT=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c 1-4)
          docker push ghcr.io/dune-daq/microservices_dependencies:latest``
          docker push ghcr.io/dune-daq/microservices:$COMMIT_SHA_SHORT